background {
    color = {{colors.background.default.hex}}
}

input-field {
    border_color = {{colors.primary.default.hex}}
    inner_color = {{colors.surface_container.default.hex}}
    outer_color = {{colors.background.default.hex}}
    check_color = {{colors.primary.default.hex}}
    fail_color = {{colors.error.default.hex}}
    font_color = {{colors.on_background.default.hex}}
}

label {
    text = "$TIME"
    color = {{colors.on_background.default.hex}}
}
