background {{colors.background.default.hex}}
foreground {{colors.on_background.default.hex}}
cursor {{colors.primary.default.hex}}
cursor_text_color {{colors.on_primary.default.hex}}
selection_background {{colors.primary.default.hex}}
selection_foreground {{colors.on_primary.default.hex}}
active_border_color {{colors.primary.default.hex}}
inactive_border_color {{colors.outline.default.hex}}
url_color {{colors.secondary.default.hex}}
