[global]
border-color={{colors.primary.default.hex}}
text-color={{colors.on_background.default.hex}}
background-color={{colors.background.default.hex}}
progress-color=source over {{colors.primary.default.hex}}

[urgency=low]
border-color={{colors.outline.default.hex}}
background-color={{colors.surface_container.default.hex}}
text-color={{colors.on_surface.default.hex}}

[urgency=normal]
border-color={{colors.primary.default.hex}}
background-color={{colors.background.default.hex}}
text-color={{colors.on_background.default.hex}}

[urgency=high]
border-color={{colors.error.default.hex}}
background-color={{colors.error.default.hex}}
text-color={{colors.on_error.default.hex}}
