background #141318
foreground #e6e1e9
cursor #cdbdff
cursor_text_color #34275e
selection_background #cdbdff
selection_foreground #34275e
active_border_color #cdbdff
inactive_border_color #938f99
url_color #cac3dc
